language: go

go:
 - 1.12.x
 - 1.11.x
 - 1.10.x
 - master

script:
 - go test ./...

before_install:
 - go get gonum.org/v1/gonum/floats
 - go get gonum.org/v1/gonum/optimize
 - go get github.com/kshedden/statmodel/statmodel
 - go get github.com/kshedden/dstream/dstream
 - go get github.com/kshedden/dstream/formula

